devclub-iitd/ShareACab

- lib/main.dart
- lib/screens/authenticate/forgotpass.dart
- lib/screens/authenticate/register.dart
- lib/screens/authenticate/sign_in.dart
- lib/screens/authenticate/verified_email_check.dart
- lib/screens/notifications.dart
- lib/screens/rootscreen.dart
- lib/screens/settings.dart
- lib/screens/userprofile.dart
- lib/shared/constants.dart
- lib/shared/loading.dart
- pubspec.lock
- pubspec.yaml
color schemes can be adjusted later. Button to switch working, and also state of dark mode toggle is getting saved.
> add darkmode and some UI changes

- lib/screens/tripslist.dart
- lib/services/database.dart
small change, but this was important, please merge ASAP
> save timestamp in groups/request and fix order

- lib/screens/rootscreen.dart
> changed icons on choosing screen

- lib/screens/profile/userprofile.dart
Added the actual email of the user on the profile page, and the first letter of the name to the Profile (Replacing the "D")
> Changed the dummy email to the actual email of the current user & Added the first letter of the user name to the profile logo

- lib/screens/notifications/notifications.dart
- lib/screens/requests/myrequests.dart
- lib/screens/tripslist.dart
Added that ripple thing to cards in myrequests.dart and in notifications.dart. Also, gave font weight to status in request cards.
Fixes #71
> List Tiles added to notifs and requests and fix size of container changed

- lib/screens/authenticate/forgotpass.dart
- lib/screens/authenticate/register.dart
- lib/screens/authenticate/sign_in.dart
- lib/screens/chatscreen/chat_database/database.dart
- lib/screens/chatscreen/chat_widgets/chat_tile.dart
- lib/screens/chatscreen/chat_widgets/chat_users_list.dart
- lib/screens/createtrip.dart
- lib/screens/dashboard.dart
- lib/screens/groupscreen/group.dart
- lib/screens/rootscreen.dart
- lib/screens/tripslist.dart
- lib/services/database.dart
* Fixed a major message screen bug #82 
* Fixed leave group button bug #83 
* Added tooltip #81 
* Fixed color schemes in auth screens
* Updated destinations to include more destinations, also accounted for the change in icons.
Fixed #82, fixed #83, fixed #81
> Major bug fixes and slight improvements

- functions/package-lock.json
Fixes the security vulnerability in websocket-extensions (https://github.com/advisories/GHSA-g78m-2chm-r7qv)
@Ishaan21 Check if something broke due to the upgrades.
> Upgrade npm packages

- lib/screens/chatscreen/chat_widgets/chat_bubble.dart
Fixes #66 
Fixes #39 
Aligned chat message text.
Also changed the chat bubble widths.
Keyboard hiding issue was already resolved.
> Improved Chat UI

- lib/models/requestdetails.dart
- lib/screens/createtrip.dart
- lib/screens/tripslist.dart
- lib/services/database.dart
While creating trip, asking user for maximum allowable users and adding it to db.  Fixes #92
> MaxPoolers

- lib/screens/authenticate/forgotpass.dart
- lib/screens/authenticate/sign_in.dart
- lib/screens/requests/myrequests.dart
- lib/screens/settings.dart
- lib/screens/tripslist.dart
Following changes are made in this PR:
1. Changed the message while theme change.
2. Similar goes with the tip in the sign in page.
3. The cards in triplist showed background container (in light theme)
4. Made the app bar of sign_in.dart consistent
5. The "view message" was not visible earlier in light theme
6. Here, color was not consistent
> Enhanced light theme

- ios/Podfile.lock
- lib/main.dart
- lib/screens/authenticate/register.dart
- lib/screens/authenticate/sign_in.dart
- lib/screens/dashboard.dart
- lib/screens/edituserdetails.dart
- lib/screens/groupdetailscreen/groupdetails.dart
- lib/screens/groupscreen/group.dart
- lib/screens/notifications/notifications.dart
- lib/screens/profile/userprofile.dart
- lib/screens/requests/myrequests.dart
- lib/screens/rootscreen.dart
- lib/screens/settings.dart
- lib/screens/tripslist.dart
Fixes #98 
Following are the changes:
1. Shifted Logout from dashboard to user profile and in settings
2. The card in group details had unnecessary top padding. So, adjusted the margin and padding of the card in group details
3. Following were icon changes (includes color change and icon removal)
4. Removed the bounce scrolling from notifications and triplist.
5. While leaving the group the color of "Leave Group" changed to black. That was to showcase that the button is disabled. But now the loading (while leaving the group) is replaced by the standard loading (as in sign out)
6. Removed the "Already in a Group Text" from top and from cards.
> UI improvements

- lib/screens/rootscreen.dart
1. Navigation using CurvedNavigationBar
2. Navigation using swipe
> Swipe feature added to toggle between screens

- lib/screens/chatscreen/chat_widgets/new_message.dart
- lib/screens/createtrip.dart
- lib/screens/groupdetailscreen/appbar.dart
- lib/screens/groupdetailscreen/groupdetails.dart
- lib/screens/groupscreen/group.dart
- lib/screens/tripslist.dart
1. After sending a message, unlike earlier now the user can't send last message even after clearing the field. Fixes #102 
2. Create Trip Validation, Fixes #101 
Note: DropDownButton and Date/Time picker cant be validated, so showing a snackbar in their case.
3. Alert Dialog on clicking Join Now, Fixes #100 
4. Group Details Screen now Updating immediately, Fixes #103 
Note: Also, on group page screen a memory leak error used to appear, solved that too.
> Chat, Alert and Validation

- lib/main.dart
- lib/screens/authenticate/change_email.dart
- lib/screens/authenticate/forgotpass.dart
- lib/screens/authenticate/register.dart
- lib/screens/authenticate/sign_in.dart
- lib/screens/edituserdetails.dart
- lib/screens/filter.dart
- lib/screens/messages.dart
- lib/shared/constants.dart
Major Input Text Fields were inconsistent and had "random" colors to border and text fields.
I am attaching screenshots for both the themes.
Also, I have deleted constants.dart as it was overwriting the standard colors defined in main.dart
Following are the changes in detail:
1. The switch color in filter.dart
2. Removed the search icon from messages (as discussed in the meeting, there is no point in providing search functionality in messages. Earlier, it used to throw "unimplemented error"
3. The Input text field had this annoying color of Text Selection Handle. So, replaced it with accent color. Also, focused border had inconsistent orange color in light theme 
4. The general enabled border of Text Fields was used as white. So, shifted the color definition to main.dart according to …
> UI consistency

- lib/screens/authenticate/register.dart
- lib/screens/chatscreen/chat_widgets/new_message.dart
- lib/screens/groupdetailscreen/groupdetails.dart
- lib/screens/tripslist.dart
- lib/services/database.dart
* The members of group update instantly now in group details page..
* Updating the admin when the admin leaves the group to the oldest member.
* Fixed typo on sign-up screen.
* Fixed font size on cards on dashboard for smaller devices.
* Fixed the delay in chat screen which appeared after sending a message.
> Multiple bug fixes and improvements

- lib/screens/authenticate/verified_email_check.dart
- lib/screens/dashboard.dart
- lib/screens/groupscreen/group.dart
- lib/screens/profile/userprofile.dart
1. While loading a page, app bar is shown in most of the screens. So, stream builder is placed outside app bar (in dashboard and user profile page). 
2. verified email check had a very poor color for texts and icons (text was not visible in light theme). Also, standard colors were not used.
> stream builder placed after app bar and UI changes in email check

- lib/screens/groupscreen/group.dart
- lib/screens/notifications/notifications.dart
- lib/screens/notifications/services/database.dart
- lib/screens/notifications/services/notifservices.dart
- lib/screens/notifications/widgets/notiftile.dart
1. Remove All Notifications feature added.
2. Also, Swipe to delete has been implemented.
Fixes #133
> Swipe to delete and Remove all notifs feature added

- lib/screens/dashboard.dart
- lib/screens/filter.dart
- lib/screens/tripslist.dart
Filtering Data on the basis of :
1. Destination
2. Privacy of groups.
Fixes #46 
Fixes #3
> Filter working

- README.md
- lib/screens/authenticate/verified_email_check.dart
- lib/screens/createtrip.dart
- lib/screens/groupdetailscreen/groupdetails.dart
- lib/screens/notifications/services/database.dart
- lib/screens/tripslist.dart
- lib/screens/wrapper.dart
- lib/services/database.dart
* Fixed log in screen showing for a few seconds when app is opened despite user being logged in. fixes #136 
* Highlighting the current group on dashboard implemented.
* Highlighting groups to which request has been sent implemented.
* Also a bug fix while joining group.
> Bug fixes and UI enhancements

- lib/screens/createtrip.dart
Create Trip Form is Validating properly now
Fixes #138
> Validating Form on Creating Trip

- lib/screens/authenticate/register.dart
- lib/screens/dashboard.dart
- lib/screens/messages.dart
- lib/screens/notifications/notifications.dart
- lib/screens/profile/userprofile.dart
- lib/screens/requests/myrequests.dart
> will pop scope added to screens

- lib/screens/chatscreen/chat_widgets/chat_bubble.dart
- lib/screens/chatscreen/chat_widgets/message.dart
- pubspec.lock
Fixes #153 
Please let me know if any changes are required @kshitijalwadhi
> Add timestamp in message bubbles on chat screen

- lib/screens/dashboard.dart
- lib/screens/tripslist.dart
- lib/shared/globals.dart
Fixes #145 and the problem faced in #162.
Working demo:
@kshitijalwadhi @Deepanshu-Rohilla  Let me know any changes if required.
> Restructure FAB and fix FAB while scroll
